### ISSUE TITLE
add LDM_res

### ISSUE THREAD

**Issue by franchg** [hoonerg/Awesome-Diffusion-Models-for-Weather-Forecasting#1]
Hi! our paper may be of interest, Latent diffusion model for meteorological downscaling:
https://github.com/DSIP-FBK/DiffScaler

It is based on an adaptation of LDCast, if you like to check it out

**Comment by hoonerg** [comment]
Hi, thank you for the information. I’ve now added it to the list.

**Comment by franchg** [comment]
thanks! the Date should be 2024.06 since we published in june

**Comment by hoonerg** [comment]
Sure it's now fixed.
